[package]
name = "toktrie_tiktoken"
version = "0.1.0"
edition = "2021"

[dependencies]
toktrie = { path = "../core" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
anyhow = "1.0.75"
rustc-hash = { version = "2.0.0" }
log = "0.4.21"
tiktoken-rs = "0.5.9"
